name: Minify and Deploy HTML


permissions:
  contents: write

on:
  push:
    branches:
      - source

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          ref: source

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install html-minifier
        run: npm install -g html-minifier

      - name: Minify HTML files
        run: |
          mkdir minified
          find . -name '*.html' -not -path './minified/*' -exec sh -c \
            'html-minifier --collapse-whitespace --remove-comments --minify-css true --minify-js true -o minified/$(basename "$1") "$1"' _ {} \;

      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          path: main_branch

      - name: Copy minified files to main branch
        run: |
          cp minified/*.html main_branch/
          cd main_branch
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add *.html
          git commit -m "Minified HTML files from source branch" || echo "No changes to commit"
          git push origin main