name: Build and Deploy to GitHub Pages

on:
  push:
    branches: [source]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js (if needed)
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Run build script
        run: |
          chmod +x build.sh
          ./build.sh

      - name: Configure Git identity
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to main/docs
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          publish_branch: main
          destination_dir: docs